# Generated by Django 2.0.4 on 2018-10-29 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_presentacion_pedido', models.IntegerField(blank=True, null=True)),
                ('cantidad_presentacion_entrega', models.IntegerField(blank=True, null=True)),
                ('cantidad_unidad_pedido', models.IntegerField(blank=True, null=True)),
                ('cantidad_unidad_entrega', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_oferta', models.BooleanField(default=False)),
                ('is_nodeseado', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('impuesto', models.ManyToManyField(to='maestro.Impuesto')),
                ('presentacionxproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.PresentacionxProducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('1', 'PRODUCTO'), ('2', 'DESCUENTO MONETARIO'), ('3', 'DESCUENTO PORCENTUAL')], max_length=1)),
                ('tipo_duracion', models.CharField(choices=[('1', 'TEMPORAL'), ('2', 'PERMANENTE')], max_length=1)),
                ('cantidad_oferta', models.IntegerField()),
                ('cantidad_unidad_oferta', models.IntegerField(blank=True, null=True)),
                ('retorno', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fechahora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fechahora_fin', models.DateTimeField(blank=True, null=True)),
                ('stock_limite', models.IntegerField(blank=True, null=True)),
                ('stock_faltante', models.IntegerField(blank=True, null=True)),
                ('presentacion_oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentacion_oferta_venta', to='maestro.PresentacionxProducto')),
                ('presentacion_retorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presentacion_retorno_venta', to='maestro.PresentacionxProducto')),
                ('producto_oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_oferta_venta', to='maestro.Producto')),
                ('producto_retorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_retorno_venta', to='maestro.Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'GENERADO'), ('2', 'CONVERTIDO A PEDIDO'), ('3', 'VENTA'), ('4', 'CANCELADO'), ('5', 'OCUPADO')], default=1, max_length=1)),
                ('tipo', models.CharField(choices=[('1', 'VENTA DIRECTA'), ('2', 'PEDIDO')], default=1, max_length=1)),
                ('tipo_pago', models.CharField(choices=[('1', 'CONTADO'), ('2', 'CREDITO')], default=1, max_length=1)),
                ('estado_pago', models.CharField(choices=[('1', 'EN DEUDA'), ('2', 'PAGADO')], default=1, max_length=1)),
                ('fechahora_creacion', models.DateTimeField(auto_now_add=True)),
                ('serie_comprobante', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_pagado', models.BooleanField(default=False)),
                ('is_entregado', models.BooleanField(default=False)),
                ('asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Sucursal')),
                ('tipo_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestro.TipoComprobante')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
    ]
