# Generated by Django 2.0.4 on 2018-11-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
