# Generated by Django 2.0.4 on 2018-11-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0004_asignaciongrupo_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestro.Empresa'),
            preserve_default=False,
        ),
    ]
