# Generated by Django 2.0.4 on 2018-10-29 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'PERSONA'), ('2', 'EMPRESARIAL')], default=1, max_length=1)),
                ('documento', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=250)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=250, null=True)),
                ('nombres', models.CharField(blank=True, max_length=250, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('cargo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
