# Generated by Django 2.0.4 on 2018-11-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0005_proveedor_empresa'),
        ('clientes', '0002_auto_20181115_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestro.Empresa'),
            preserve_default=False,
        ),
    ]
