# Generated by Django 2.0.4 on 2018-10-29 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestro', '0001_initial'),
        ('compras', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[(1, 'ENTRADA'), (2, 'SALIDA')], max_length=1)),
                ('tipo_detalle', models.CharField(choices=[(1, 'COMPRA'), (2, 'VENTA'), (3, 'REEMBOLSO COMPRA'), (4, 'REEMBOLSO VENTA')], max_length=1)),
                ('cantidad', models.IntegerField()),
                ('cantidad_entrada', models.IntegerField(blank=True, null=True)),
                ('cantidad_salida', models.IntegerField(blank=True, null=True)),
                ('precio_unitario_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_unitario_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cantidad_saldo', models.IntegerField()),
                ('precio_unitario_saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechahora', models.DateTimeField(auto_now_add=True)),
                ('serie_comprobante', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=10, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.Almacen')),
                ('detallecompra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.DetalleCompra')),
                ('detalleventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.DetalleVenta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Producto')),
                ('tipo_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestro.TipoComprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.Almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestro.Producto')),
            ],
        ),
    ]
