# Generated by Django 2.0.4 on 2018-10-29 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'GENERADO'), ('2', 'CONVERTIDO A PEDIDO'), ('3', 'COMPRA'), ('4', 'CANCELADO'), ('5', 'OCUPADO')], default=1, max_length=1)),
                ('tipo', models.CharField(choices=[('1', 'COMPRA DIRECTA'), ('2', 'PEDIDO')], default=1, max_length=1)),
                ('is_financiado', models.BooleanField(default=False)),
                ('is_entregado', models.BooleanField(default=False)),
                ('fechahora_creacion', models.DateTimeField(auto_now_add=True)),
                ('serie_comprobante', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Almacen')),
                ('asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Proveedor')),
                ('tipo_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestro.TipoComprobante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_presentacion_pedido', models.IntegerField(blank=True, null=True)),
                ('cantidad_presentacion_entrega', models.IntegerField(blank=True, null=True)),
                ('cantidad_unidad_pedido', models.IntegerField(blank=True, null=True)),
                ('cantidad_unidad_entrega', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('impuesto_monto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_final', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_oferta', models.BooleanField(default=False)),
                ('is_nodeseado', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Compra')),
                ('impuesto', models.ManyToManyField(to='maestro.Impuesto')),
                ('presentacionxproducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.PresentacionxProducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestro.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(1, 'PRODUCTO'), (2, 'DESCUENTO MONETARIO'), (3, 'DESCUENTO PORCENTUAL')], max_length=1)),
                ('cantidad_compra', models.IntegerField()),
                ('retorno', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('detallecompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.DetalleCompra')),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presentacion_oferta', to='maestro.PresentacionxProducto')),
                ('presentacion_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentacion_compra', to='maestro.PresentacionxProducto')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestro.Producto')),
            ],
        ),
    ]
