# Generated by Django 2.0.4 on 2018-10-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_pago',
            field=models.CharField(choices=[('1', 'EN DEUDA'), ('2', 'PAGADO')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_pago',
            field=models.CharField(choices=[('1', 'CONTADO'), ('2', 'CREDITO')], default=1, max_length=1),
        ),
    ]
